// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: JobMonitorService.proto

package org.kesy.djob.sdu.api.model;

public final class JobMonitorServiceProto {
  private JobMonitorServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface SearchJobMonitorsParamOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional string jobName = 1;
    boolean hasJobName();
    String getJobName();
    
    // optional string runStatus = 2;
    boolean hasRunStatus();
    String getRunStatus();
    
    // optional int32 pageIndex = 3;
    boolean hasPageIndex();
    int getPageIndex();
    
    // optional int32 pageSize = 4;
    boolean hasPageSize();
    int getPageSize();
    
    // optional string startTime = 5;
    boolean hasStartTime();
    String getStartTime();
    
    // optional string endTime = 6;
    boolean hasEndTime();
    String getEndTime();
  }
  public static final class SearchJobMonitorsParam extends
      com.google.protobuf.GeneratedMessage
      implements SearchJobMonitorsParamOrBuilder {
    // Use SearchJobMonitorsParam.newBuilder() to construct.
    private SearchJobMonitorsParam(Builder builder) {
      super(builder);
    }
    private SearchJobMonitorsParam(boolean noInit) {}
    
    private static final SearchJobMonitorsParam defaultInstance;
    public static SearchJobMonitorsParam getDefaultInstance() {
      return defaultInstance;
    }
    
    public SearchJobMonitorsParam getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.kesy.djob.sdu.api.model.JobMonitorServiceProto.internal_static_org_kesy_djob_sdu_api_model_SearchJobMonitorsParam_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.kesy.djob.sdu.api.model.JobMonitorServiceProto.internal_static_org_kesy_djob_sdu_api_model_SearchJobMonitorsParam_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional string jobName = 1;
    public static final int JOBNAME_FIELD_NUMBER = 1;
    private java.lang.Object jobName_;
    public boolean hasJobName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getJobName() {
      java.lang.Object ref = jobName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          jobName_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getJobNameBytes() {
      java.lang.Object ref = jobName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        jobName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string runStatus = 2;
    public static final int RUNSTATUS_FIELD_NUMBER = 2;
    private java.lang.Object runStatus_;
    public boolean hasRunStatus() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getRunStatus() {
      java.lang.Object ref = runStatus_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          runStatus_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getRunStatusBytes() {
      java.lang.Object ref = runStatus_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        runStatus_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int32 pageIndex = 3;
    public static final int PAGEINDEX_FIELD_NUMBER = 3;
    private int pageIndex_;
    public boolean hasPageIndex() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getPageIndex() {
      return pageIndex_;
    }
    
    // optional int32 pageSize = 4;
    public static final int PAGESIZE_FIELD_NUMBER = 4;
    private int pageSize_;
    public boolean hasPageSize() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public int getPageSize() {
      return pageSize_;
    }
    
    // optional string startTime = 5;
    public static final int STARTTIME_FIELD_NUMBER = 5;
    private java.lang.Object startTime_;
    public boolean hasStartTime() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public String getStartTime() {
      java.lang.Object ref = startTime_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          startTime_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getStartTimeBytes() {
      java.lang.Object ref = startTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        startTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string endTime = 6;
    public static final int ENDTIME_FIELD_NUMBER = 6;
    private java.lang.Object endTime_;
    public boolean hasEndTime() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public String getEndTime() {
      java.lang.Object ref = endTime_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          endTime_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getEndTimeBytes() {
      java.lang.Object ref = endTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        endTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      jobName_ = "";
      runStatus_ = "";
      pageIndex_ = 0;
      pageSize_ = 0;
      startTime_ = "";
      endTime_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getJobNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getRunStatusBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, pageIndex_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, pageSize_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getStartTimeBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getEndTimeBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getJobNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getRunStatusBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, pageIndex_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, pageSize_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getStartTimeBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getEndTimeBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.kesy.djob.sdu.api.model.JobMonitorServiceProto.SearchJobMonitorsParam parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.kesy.djob.sdu.api.model.JobMonitorServiceProto.SearchJobMonitorsParam parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.kesy.djob.sdu.api.model.JobMonitorServiceProto.SearchJobMonitorsParam parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.kesy.djob.sdu.api.model.JobMonitorServiceProto.SearchJobMonitorsParam parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.kesy.djob.sdu.api.model.JobMonitorServiceProto.SearchJobMonitorsParam parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.kesy.djob.sdu.api.model.JobMonitorServiceProto.SearchJobMonitorsParam parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.kesy.djob.sdu.api.model.JobMonitorServiceProto.SearchJobMonitorsParam parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.kesy.djob.sdu.api.model.JobMonitorServiceProto.SearchJobMonitorsParam parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.kesy.djob.sdu.api.model.JobMonitorServiceProto.SearchJobMonitorsParam parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.kesy.djob.sdu.api.model.JobMonitorServiceProto.SearchJobMonitorsParam parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.kesy.djob.sdu.api.model.JobMonitorServiceProto.SearchJobMonitorsParam prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.kesy.djob.sdu.api.model.JobMonitorServiceProto.SearchJobMonitorsParamOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.kesy.djob.sdu.api.model.JobMonitorServiceProto.internal_static_org_kesy_djob_sdu_api_model_SearchJobMonitorsParam_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.kesy.djob.sdu.api.model.JobMonitorServiceProto.internal_static_org_kesy_djob_sdu_api_model_SearchJobMonitorsParam_fieldAccessorTable;
      }
      
      // Construct using org.kesy.djob.sdu.api.model.JobMonitorServiceProto.SearchJobMonitorsParam.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        jobName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        runStatus_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        pageIndex_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        pageSize_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        startTime_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        endTime_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.kesy.djob.sdu.api.model.JobMonitorServiceProto.SearchJobMonitorsParam.getDescriptor();
      }
      
      public org.kesy.djob.sdu.api.model.JobMonitorServiceProto.SearchJobMonitorsParam getDefaultInstanceForType() {
        return org.kesy.djob.sdu.api.model.JobMonitorServiceProto.SearchJobMonitorsParam.getDefaultInstance();
      }
      
      public org.kesy.djob.sdu.api.model.JobMonitorServiceProto.SearchJobMonitorsParam build() {
        org.kesy.djob.sdu.api.model.JobMonitorServiceProto.SearchJobMonitorsParam result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.kesy.djob.sdu.api.model.JobMonitorServiceProto.SearchJobMonitorsParam buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.kesy.djob.sdu.api.model.JobMonitorServiceProto.SearchJobMonitorsParam result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.kesy.djob.sdu.api.model.JobMonitorServiceProto.SearchJobMonitorsParam buildPartial() {
        org.kesy.djob.sdu.api.model.JobMonitorServiceProto.SearchJobMonitorsParam result = new org.kesy.djob.sdu.api.model.JobMonitorServiceProto.SearchJobMonitorsParam(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.jobName_ = jobName_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.runStatus_ = runStatus_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.pageIndex_ = pageIndex_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.pageSize_ = pageSize_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.startTime_ = startTime_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.endTime_ = endTime_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.kesy.djob.sdu.api.model.JobMonitorServiceProto.SearchJobMonitorsParam) {
          return mergeFrom((org.kesy.djob.sdu.api.model.JobMonitorServiceProto.SearchJobMonitorsParam)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.kesy.djob.sdu.api.model.JobMonitorServiceProto.SearchJobMonitorsParam other) {
        if (other == org.kesy.djob.sdu.api.model.JobMonitorServiceProto.SearchJobMonitorsParam.getDefaultInstance()) return this;
        if (other.hasJobName()) {
          setJobName(other.getJobName());
        }
        if (other.hasRunStatus()) {
          setRunStatus(other.getRunStatus());
        }
        if (other.hasPageIndex()) {
          setPageIndex(other.getPageIndex());
        }
        if (other.hasPageSize()) {
          setPageSize(other.getPageSize());
        }
        if (other.hasStartTime()) {
          setStartTime(other.getStartTime());
        }
        if (other.hasEndTime()) {
          setEndTime(other.getEndTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              jobName_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              runStatus_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              pageIndex_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              pageSize_ = input.readInt32();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              startTime_ = input.readBytes();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              endTime_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string jobName = 1;
      private java.lang.Object jobName_ = "";
      public boolean hasJobName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getJobName() {
        java.lang.Object ref = jobName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          jobName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setJobName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        jobName_ = value;
        onChanged();
        return this;
      }
      public Builder clearJobName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        jobName_ = getDefaultInstance().getJobName();
        onChanged();
        return this;
      }
      void setJobName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        jobName_ = value;
        onChanged();
      }
      
      // optional string runStatus = 2;
      private java.lang.Object runStatus_ = "";
      public boolean hasRunStatus() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getRunStatus() {
        java.lang.Object ref = runStatus_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          runStatus_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setRunStatus(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        runStatus_ = value;
        onChanged();
        return this;
      }
      public Builder clearRunStatus() {
        bitField0_ = (bitField0_ & ~0x00000002);
        runStatus_ = getDefaultInstance().getRunStatus();
        onChanged();
        return this;
      }
      void setRunStatus(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        runStatus_ = value;
        onChanged();
      }
      
      // optional int32 pageIndex = 3;
      private int pageIndex_ ;
      public boolean hasPageIndex() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getPageIndex() {
        return pageIndex_;
      }
      public Builder setPageIndex(int value) {
        bitField0_ |= 0x00000004;
        pageIndex_ = value;
        onChanged();
        return this;
      }
      public Builder clearPageIndex() {
        bitField0_ = (bitField0_ & ~0x00000004);
        pageIndex_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 pageSize = 4;
      private int pageSize_ ;
      public boolean hasPageSize() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public int getPageSize() {
        return pageSize_;
      }
      public Builder setPageSize(int value) {
        bitField0_ |= 0x00000008;
        pageSize_ = value;
        onChanged();
        return this;
      }
      public Builder clearPageSize() {
        bitField0_ = (bitField0_ & ~0x00000008);
        pageSize_ = 0;
        onChanged();
        return this;
      }
      
      // optional string startTime = 5;
      private java.lang.Object startTime_ = "";
      public boolean hasStartTime() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public String getStartTime() {
        java.lang.Object ref = startTime_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          startTime_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setStartTime(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        startTime_ = value;
        onChanged();
        return this;
      }
      public Builder clearStartTime() {
        bitField0_ = (bitField0_ & ~0x00000010);
        startTime_ = getDefaultInstance().getStartTime();
        onChanged();
        return this;
      }
      void setStartTime(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000010;
        startTime_ = value;
        onChanged();
      }
      
      // optional string endTime = 6;
      private java.lang.Object endTime_ = "";
      public boolean hasEndTime() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public String getEndTime() {
        java.lang.Object ref = endTime_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          endTime_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setEndTime(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        endTime_ = value;
        onChanged();
        return this;
      }
      public Builder clearEndTime() {
        bitField0_ = (bitField0_ & ~0x00000020);
        endTime_ = getDefaultInstance().getEndTime();
        onChanged();
        return this;
      }
      void setEndTime(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000020;
        endTime_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:org.kesy.djob.sdu.api.model.SearchJobMonitorsParam)
    }
    
    static {
      defaultInstance = new SearchJobMonitorsParam(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:org.kesy.djob.sdu.api.model.SearchJobMonitorsParam)
  }
  
  public interface GetTaskMonitorsParamOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional string jobId = 1;
    boolean hasJobId();
    String getJobId();
    
    // optional int32 pageIndex = 2;
    boolean hasPageIndex();
    int getPageIndex();
    
    // optional int32 pageSize = 3;
    boolean hasPageSize();
    int getPageSize();
  }
  public static final class GetTaskMonitorsParam extends
      com.google.protobuf.GeneratedMessage
      implements GetTaskMonitorsParamOrBuilder {
    // Use GetTaskMonitorsParam.newBuilder() to construct.
    private GetTaskMonitorsParam(Builder builder) {
      super(builder);
    }
    private GetTaskMonitorsParam(boolean noInit) {}
    
    private static final GetTaskMonitorsParam defaultInstance;
    public static GetTaskMonitorsParam getDefaultInstance() {
      return defaultInstance;
    }
    
    public GetTaskMonitorsParam getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.kesy.djob.sdu.api.model.JobMonitorServiceProto.internal_static_org_kesy_djob_sdu_api_model_GetTaskMonitorsParam_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.kesy.djob.sdu.api.model.JobMonitorServiceProto.internal_static_org_kesy_djob_sdu_api_model_GetTaskMonitorsParam_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional string jobId = 1;
    public static final int JOBID_FIELD_NUMBER = 1;
    private java.lang.Object jobId_;
    public boolean hasJobId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getJobId() {
      java.lang.Object ref = jobId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          jobId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getJobIdBytes() {
      java.lang.Object ref = jobId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        jobId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int32 pageIndex = 2;
    public static final int PAGEINDEX_FIELD_NUMBER = 2;
    private int pageIndex_;
    public boolean hasPageIndex() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getPageIndex() {
      return pageIndex_;
    }
    
    // optional int32 pageSize = 3;
    public static final int PAGESIZE_FIELD_NUMBER = 3;
    private int pageSize_;
    public boolean hasPageSize() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getPageSize() {
      return pageSize_;
    }
    
    private void initFields() {
      jobId_ = "";
      pageIndex_ = 0;
      pageSize_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getJobIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, pageIndex_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, pageSize_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getJobIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, pageIndex_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, pageSize_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.kesy.djob.sdu.api.model.JobMonitorServiceProto.GetTaskMonitorsParam parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.kesy.djob.sdu.api.model.JobMonitorServiceProto.GetTaskMonitorsParam parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.kesy.djob.sdu.api.model.JobMonitorServiceProto.GetTaskMonitorsParam parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.kesy.djob.sdu.api.model.JobMonitorServiceProto.GetTaskMonitorsParam parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.kesy.djob.sdu.api.model.JobMonitorServiceProto.GetTaskMonitorsParam parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.kesy.djob.sdu.api.model.JobMonitorServiceProto.GetTaskMonitorsParam parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.kesy.djob.sdu.api.model.JobMonitorServiceProto.GetTaskMonitorsParam parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.kesy.djob.sdu.api.model.JobMonitorServiceProto.GetTaskMonitorsParam parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.kesy.djob.sdu.api.model.JobMonitorServiceProto.GetTaskMonitorsParam parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.kesy.djob.sdu.api.model.JobMonitorServiceProto.GetTaskMonitorsParam parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.kesy.djob.sdu.api.model.JobMonitorServiceProto.GetTaskMonitorsParam prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.kesy.djob.sdu.api.model.JobMonitorServiceProto.GetTaskMonitorsParamOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.kesy.djob.sdu.api.model.JobMonitorServiceProto.internal_static_org_kesy_djob_sdu_api_model_GetTaskMonitorsParam_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.kesy.djob.sdu.api.model.JobMonitorServiceProto.internal_static_org_kesy_djob_sdu_api_model_GetTaskMonitorsParam_fieldAccessorTable;
      }
      
      // Construct using org.kesy.djob.sdu.api.model.JobMonitorServiceProto.GetTaskMonitorsParam.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        jobId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        pageIndex_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        pageSize_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.kesy.djob.sdu.api.model.JobMonitorServiceProto.GetTaskMonitorsParam.getDescriptor();
      }
      
      public org.kesy.djob.sdu.api.model.JobMonitorServiceProto.GetTaskMonitorsParam getDefaultInstanceForType() {
        return org.kesy.djob.sdu.api.model.JobMonitorServiceProto.GetTaskMonitorsParam.getDefaultInstance();
      }
      
      public org.kesy.djob.sdu.api.model.JobMonitorServiceProto.GetTaskMonitorsParam build() {
        org.kesy.djob.sdu.api.model.JobMonitorServiceProto.GetTaskMonitorsParam result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.kesy.djob.sdu.api.model.JobMonitorServiceProto.GetTaskMonitorsParam buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.kesy.djob.sdu.api.model.JobMonitorServiceProto.GetTaskMonitorsParam result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.kesy.djob.sdu.api.model.JobMonitorServiceProto.GetTaskMonitorsParam buildPartial() {
        org.kesy.djob.sdu.api.model.JobMonitorServiceProto.GetTaskMonitorsParam result = new org.kesy.djob.sdu.api.model.JobMonitorServiceProto.GetTaskMonitorsParam(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.jobId_ = jobId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.pageIndex_ = pageIndex_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.pageSize_ = pageSize_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.kesy.djob.sdu.api.model.JobMonitorServiceProto.GetTaskMonitorsParam) {
          return mergeFrom((org.kesy.djob.sdu.api.model.JobMonitorServiceProto.GetTaskMonitorsParam)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.kesy.djob.sdu.api.model.JobMonitorServiceProto.GetTaskMonitorsParam other) {
        if (other == org.kesy.djob.sdu.api.model.JobMonitorServiceProto.GetTaskMonitorsParam.getDefaultInstance()) return this;
        if (other.hasJobId()) {
          setJobId(other.getJobId());
        }
        if (other.hasPageIndex()) {
          setPageIndex(other.getPageIndex());
        }
        if (other.hasPageSize()) {
          setPageSize(other.getPageSize());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              jobId_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              pageIndex_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              pageSize_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string jobId = 1;
      private java.lang.Object jobId_ = "";
      public boolean hasJobId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getJobId() {
        java.lang.Object ref = jobId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          jobId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setJobId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        jobId_ = value;
        onChanged();
        return this;
      }
      public Builder clearJobId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        jobId_ = getDefaultInstance().getJobId();
        onChanged();
        return this;
      }
      void setJobId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        jobId_ = value;
        onChanged();
      }
      
      // optional int32 pageIndex = 2;
      private int pageIndex_ ;
      public boolean hasPageIndex() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getPageIndex() {
        return pageIndex_;
      }
      public Builder setPageIndex(int value) {
        bitField0_ |= 0x00000002;
        pageIndex_ = value;
        onChanged();
        return this;
      }
      public Builder clearPageIndex() {
        bitField0_ = (bitField0_ & ~0x00000002);
        pageIndex_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 pageSize = 3;
      private int pageSize_ ;
      public boolean hasPageSize() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getPageSize() {
        return pageSize_;
      }
      public Builder setPageSize(int value) {
        bitField0_ |= 0x00000004;
        pageSize_ = value;
        onChanged();
        return this;
      }
      public Builder clearPageSize() {
        bitField0_ = (bitField0_ & ~0x00000004);
        pageSize_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:org.kesy.djob.sdu.api.model.GetTaskMonitorsParam)
    }
    
    static {
      defaultInstance = new GetTaskMonitorsParam(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:org.kesy.djob.sdu.api.model.GetTaskMonitorsParam)
  }
  
  public static abstract class JobMonitorService
      implements com.google.protobuf.Service {
    protected JobMonitorService() {}
    
    public interface Interface {
      public abstract void searchJobMonitorCount(
          com.google.protobuf.RpcController controller,
          org.kesy.djob.sdu.api.model.JobMonitorServiceProto.SearchJobMonitorsParam request,
          com.google.protobuf.RpcCallback<org.kesy.djob.sdu.api.model.JobInfoModels.IntegerType> done);
      
      public abstract void searchJobMonitors(
          com.google.protobuf.RpcController controller,
          org.kesy.djob.sdu.api.model.JobMonitorServiceProto.SearchJobMonitorsParam request,
          com.google.protobuf.RpcCallback<org.kesy.djob.sdu.api.model.JobInfoModels.JobInfoList> done);
      
      public abstract void getTaskMonitorCount(
          com.google.protobuf.RpcController controller,
          org.kesy.djob.sdu.api.model.JobInfoModels.StringType request,
          com.google.protobuf.RpcCallback<org.kesy.djob.sdu.api.model.JobInfoModels.IntegerType> done);
      
      public abstract void getTaskMonitors(
          com.google.protobuf.RpcController controller,
          org.kesy.djob.sdu.api.model.JobMonitorServiceProto.GetTaskMonitorsParam request,
          com.google.protobuf.RpcCallback<org.kesy.djob.sdu.api.model.JobInfoModels.TaskInfoList> done);
      
      public abstract void searchJobTaskMonitorCount(
          com.google.protobuf.RpcController controller,
          org.kesy.djob.sdu.api.model.JobMonitorServiceProto.SearchJobMonitorsParam request,
          com.google.protobuf.RpcCallback<org.kesy.djob.sdu.api.model.JobInfoModels.IntegerType> done);
      
      public abstract void searchJobTaskMonitors(
          com.google.protobuf.RpcController controller,
          org.kesy.djob.sdu.api.model.JobMonitorServiceProto.SearchJobMonitorsParam request,
          com.google.protobuf.RpcCallback<org.kesy.djob.sdu.api.model.JobInfoModels.TaskInfoList> done);
      
    }
    
    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new JobMonitorService() {
        @java.lang.Override
        public  void searchJobMonitorCount(
            com.google.protobuf.RpcController controller,
            org.kesy.djob.sdu.api.model.JobMonitorServiceProto.SearchJobMonitorsParam request,
            com.google.protobuf.RpcCallback<org.kesy.djob.sdu.api.model.JobInfoModels.IntegerType> done) {
          impl.searchJobMonitorCount(controller, request, done);
        }
        
        @java.lang.Override
        public  void searchJobMonitors(
            com.google.protobuf.RpcController controller,
            org.kesy.djob.sdu.api.model.JobMonitorServiceProto.SearchJobMonitorsParam request,
            com.google.protobuf.RpcCallback<org.kesy.djob.sdu.api.model.JobInfoModels.JobInfoList> done) {
          impl.searchJobMonitors(controller, request, done);
        }
        
        @java.lang.Override
        public  void getTaskMonitorCount(
            com.google.protobuf.RpcController controller,
            org.kesy.djob.sdu.api.model.JobInfoModels.StringType request,
            com.google.protobuf.RpcCallback<org.kesy.djob.sdu.api.model.JobInfoModels.IntegerType> done) {
          impl.getTaskMonitorCount(controller, request, done);
        }
        
        @java.lang.Override
        public  void getTaskMonitors(
            com.google.protobuf.RpcController controller,
            org.kesy.djob.sdu.api.model.JobMonitorServiceProto.GetTaskMonitorsParam request,
            com.google.protobuf.RpcCallback<org.kesy.djob.sdu.api.model.JobInfoModels.TaskInfoList> done) {
          impl.getTaskMonitors(controller, request, done);
        }
        
        @java.lang.Override
        public  void searchJobTaskMonitorCount(
            com.google.protobuf.RpcController controller,
            org.kesy.djob.sdu.api.model.JobMonitorServiceProto.SearchJobMonitorsParam request,
            com.google.protobuf.RpcCallback<org.kesy.djob.sdu.api.model.JobInfoModels.IntegerType> done) {
          impl.searchJobTaskMonitorCount(controller, request, done);
        }
        
        @java.lang.Override
        public  void searchJobTaskMonitors(
            com.google.protobuf.RpcController controller,
            org.kesy.djob.sdu.api.model.JobMonitorServiceProto.SearchJobMonitorsParam request,
            com.google.protobuf.RpcCallback<org.kesy.djob.sdu.api.model.JobInfoModels.TaskInfoList> done) {
          impl.searchJobTaskMonitors(controller, request, done);
        }
        
      };
    }
    
    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }
        
        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.searchJobMonitorCount(controller, (org.kesy.djob.sdu.api.model.JobMonitorServiceProto.SearchJobMonitorsParam)request);
            case 1:
              return impl.searchJobMonitors(controller, (org.kesy.djob.sdu.api.model.JobMonitorServiceProto.SearchJobMonitorsParam)request);
            case 2:
              return impl.getTaskMonitorCount(controller, (org.kesy.djob.sdu.api.model.JobInfoModels.StringType)request);
            case 3:
              return impl.getTaskMonitors(controller, (org.kesy.djob.sdu.api.model.JobMonitorServiceProto.GetTaskMonitorsParam)request);
            case 4:
              return impl.searchJobTaskMonitorCount(controller, (org.kesy.djob.sdu.api.model.JobMonitorServiceProto.SearchJobMonitorsParam)request);
            case 5:
              return impl.searchJobTaskMonitors(controller, (org.kesy.djob.sdu.api.model.JobMonitorServiceProto.SearchJobMonitorsParam)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return org.kesy.djob.sdu.api.model.JobMonitorServiceProto.SearchJobMonitorsParam.getDefaultInstance();
            case 1:
              return org.kesy.djob.sdu.api.model.JobMonitorServiceProto.SearchJobMonitorsParam.getDefaultInstance();
            case 2:
              return org.kesy.djob.sdu.api.model.JobInfoModels.StringType.getDefaultInstance();
            case 3:
              return org.kesy.djob.sdu.api.model.JobMonitorServiceProto.GetTaskMonitorsParam.getDefaultInstance();
            case 4:
              return org.kesy.djob.sdu.api.model.JobMonitorServiceProto.SearchJobMonitorsParam.getDefaultInstance();
            case 5:
              return org.kesy.djob.sdu.api.model.JobMonitorServiceProto.SearchJobMonitorsParam.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return org.kesy.djob.sdu.api.model.JobInfoModels.IntegerType.getDefaultInstance();
            case 1:
              return org.kesy.djob.sdu.api.model.JobInfoModels.JobInfoList.getDefaultInstance();
            case 2:
              return org.kesy.djob.sdu.api.model.JobInfoModels.IntegerType.getDefaultInstance();
            case 3:
              return org.kesy.djob.sdu.api.model.JobInfoModels.TaskInfoList.getDefaultInstance();
            case 4:
              return org.kesy.djob.sdu.api.model.JobInfoModels.IntegerType.getDefaultInstance();
            case 5:
              return org.kesy.djob.sdu.api.model.JobInfoModels.TaskInfoList.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
      };
    }
    
    public abstract void searchJobMonitorCount(
        com.google.protobuf.RpcController controller,
        org.kesy.djob.sdu.api.model.JobMonitorServiceProto.SearchJobMonitorsParam request,
        com.google.protobuf.RpcCallback<org.kesy.djob.sdu.api.model.JobInfoModels.IntegerType> done);
    
    public abstract void searchJobMonitors(
        com.google.protobuf.RpcController controller,
        org.kesy.djob.sdu.api.model.JobMonitorServiceProto.SearchJobMonitorsParam request,
        com.google.protobuf.RpcCallback<org.kesy.djob.sdu.api.model.JobInfoModels.JobInfoList> done);
    
    public abstract void getTaskMonitorCount(
        com.google.protobuf.RpcController controller,
        org.kesy.djob.sdu.api.model.JobInfoModels.StringType request,
        com.google.protobuf.RpcCallback<org.kesy.djob.sdu.api.model.JobInfoModels.IntegerType> done);
    
    public abstract void getTaskMonitors(
        com.google.protobuf.RpcController controller,
        org.kesy.djob.sdu.api.model.JobMonitorServiceProto.GetTaskMonitorsParam request,
        com.google.protobuf.RpcCallback<org.kesy.djob.sdu.api.model.JobInfoModels.TaskInfoList> done);
    
    public abstract void searchJobTaskMonitorCount(
        com.google.protobuf.RpcController controller,
        org.kesy.djob.sdu.api.model.JobMonitorServiceProto.SearchJobMonitorsParam request,
        com.google.protobuf.RpcCallback<org.kesy.djob.sdu.api.model.JobInfoModels.IntegerType> done);
    
    public abstract void searchJobTaskMonitors(
        com.google.protobuf.RpcController controller,
        org.kesy.djob.sdu.api.model.JobMonitorServiceProto.SearchJobMonitorsParam request,
        com.google.protobuf.RpcCallback<org.kesy.djob.sdu.api.model.JobInfoModels.TaskInfoList> done);
    
    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return org.kesy.djob.sdu.api.model.JobMonitorServiceProto.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    
    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.searchJobMonitorCount(controller, (org.kesy.djob.sdu.api.model.JobMonitorServiceProto.SearchJobMonitorsParam)request,
            com.google.protobuf.RpcUtil.<org.kesy.djob.sdu.api.model.JobInfoModels.IntegerType>specializeCallback(
              done));
          return;
        case 1:
          this.searchJobMonitors(controller, (org.kesy.djob.sdu.api.model.JobMonitorServiceProto.SearchJobMonitorsParam)request,
            com.google.protobuf.RpcUtil.<org.kesy.djob.sdu.api.model.JobInfoModels.JobInfoList>specializeCallback(
              done));
          return;
        case 2:
          this.getTaskMonitorCount(controller, (org.kesy.djob.sdu.api.model.JobInfoModels.StringType)request,
            com.google.protobuf.RpcUtil.<org.kesy.djob.sdu.api.model.JobInfoModels.IntegerType>specializeCallback(
              done));
          return;
        case 3:
          this.getTaskMonitors(controller, (org.kesy.djob.sdu.api.model.JobMonitorServiceProto.GetTaskMonitorsParam)request,
            com.google.protobuf.RpcUtil.<org.kesy.djob.sdu.api.model.JobInfoModels.TaskInfoList>specializeCallback(
              done));
          return;
        case 4:
          this.searchJobTaskMonitorCount(controller, (org.kesy.djob.sdu.api.model.JobMonitorServiceProto.SearchJobMonitorsParam)request,
            com.google.protobuf.RpcUtil.<org.kesy.djob.sdu.api.model.JobInfoModels.IntegerType>specializeCallback(
              done));
          return;
        case 5:
          this.searchJobTaskMonitors(controller, (org.kesy.djob.sdu.api.model.JobMonitorServiceProto.SearchJobMonitorsParam)request,
            com.google.protobuf.RpcUtil.<org.kesy.djob.sdu.api.model.JobInfoModels.TaskInfoList>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return org.kesy.djob.sdu.api.model.JobMonitorServiceProto.SearchJobMonitorsParam.getDefaultInstance();
        case 1:
          return org.kesy.djob.sdu.api.model.JobMonitorServiceProto.SearchJobMonitorsParam.getDefaultInstance();
        case 2:
          return org.kesy.djob.sdu.api.model.JobInfoModels.StringType.getDefaultInstance();
        case 3:
          return org.kesy.djob.sdu.api.model.JobMonitorServiceProto.GetTaskMonitorsParam.getDefaultInstance();
        case 4:
          return org.kesy.djob.sdu.api.model.JobMonitorServiceProto.SearchJobMonitorsParam.getDefaultInstance();
        case 5:
          return org.kesy.djob.sdu.api.model.JobMonitorServiceProto.SearchJobMonitorsParam.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return org.kesy.djob.sdu.api.model.JobInfoModels.IntegerType.getDefaultInstance();
        case 1:
          return org.kesy.djob.sdu.api.model.JobInfoModels.JobInfoList.getDefaultInstance();
        case 2:
          return org.kesy.djob.sdu.api.model.JobInfoModels.IntegerType.getDefaultInstance();
        case 3:
          return org.kesy.djob.sdu.api.model.JobInfoModels.TaskInfoList.getDefaultInstance();
        case 4:
          return org.kesy.djob.sdu.api.model.JobInfoModels.IntegerType.getDefaultInstance();
        case 5:
          return org.kesy.djob.sdu.api.model.JobInfoModels.TaskInfoList.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }
    
    public static final class Stub extends org.kesy.djob.sdu.api.model.JobMonitorServiceProto.JobMonitorService implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }
      
      private final com.google.protobuf.RpcChannel channel;
      
      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }
      
      public  void searchJobMonitorCount(
          com.google.protobuf.RpcController controller,
          org.kesy.djob.sdu.api.model.JobMonitorServiceProto.SearchJobMonitorsParam request,
          com.google.protobuf.RpcCallback<org.kesy.djob.sdu.api.model.JobInfoModels.IntegerType> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          org.kesy.djob.sdu.api.model.JobInfoModels.IntegerType.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            org.kesy.djob.sdu.api.model.JobInfoModels.IntegerType.class,
            org.kesy.djob.sdu.api.model.JobInfoModels.IntegerType.getDefaultInstance()));
      }
      
      public  void searchJobMonitors(
          com.google.protobuf.RpcController controller,
          org.kesy.djob.sdu.api.model.JobMonitorServiceProto.SearchJobMonitorsParam request,
          com.google.protobuf.RpcCallback<org.kesy.djob.sdu.api.model.JobInfoModels.JobInfoList> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(1),
          controller,
          request,
          org.kesy.djob.sdu.api.model.JobInfoModels.JobInfoList.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            org.kesy.djob.sdu.api.model.JobInfoModels.JobInfoList.class,
            org.kesy.djob.sdu.api.model.JobInfoModels.JobInfoList.getDefaultInstance()));
      }
      
      public  void getTaskMonitorCount(
          com.google.protobuf.RpcController controller,
          org.kesy.djob.sdu.api.model.JobInfoModels.StringType request,
          com.google.protobuf.RpcCallback<org.kesy.djob.sdu.api.model.JobInfoModels.IntegerType> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(2),
          controller,
          request,
          org.kesy.djob.sdu.api.model.JobInfoModels.IntegerType.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            org.kesy.djob.sdu.api.model.JobInfoModels.IntegerType.class,
            org.kesy.djob.sdu.api.model.JobInfoModels.IntegerType.getDefaultInstance()));
      }
      
      public  void getTaskMonitors(
          com.google.protobuf.RpcController controller,
          org.kesy.djob.sdu.api.model.JobMonitorServiceProto.GetTaskMonitorsParam request,
          com.google.protobuf.RpcCallback<org.kesy.djob.sdu.api.model.JobInfoModels.TaskInfoList> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(3),
          controller,
          request,
          org.kesy.djob.sdu.api.model.JobInfoModels.TaskInfoList.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            org.kesy.djob.sdu.api.model.JobInfoModels.TaskInfoList.class,
            org.kesy.djob.sdu.api.model.JobInfoModels.TaskInfoList.getDefaultInstance()));
      }
      
      public  void searchJobTaskMonitorCount(
          com.google.protobuf.RpcController controller,
          org.kesy.djob.sdu.api.model.JobMonitorServiceProto.SearchJobMonitorsParam request,
          com.google.protobuf.RpcCallback<org.kesy.djob.sdu.api.model.JobInfoModels.IntegerType> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(4),
          controller,
          request,
          org.kesy.djob.sdu.api.model.JobInfoModels.IntegerType.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            org.kesy.djob.sdu.api.model.JobInfoModels.IntegerType.class,
            org.kesy.djob.sdu.api.model.JobInfoModels.IntegerType.getDefaultInstance()));
      }
      
      public  void searchJobTaskMonitors(
          com.google.protobuf.RpcController controller,
          org.kesy.djob.sdu.api.model.JobMonitorServiceProto.SearchJobMonitorsParam request,
          com.google.protobuf.RpcCallback<org.kesy.djob.sdu.api.model.JobInfoModels.TaskInfoList> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(5),
          controller,
          request,
          org.kesy.djob.sdu.api.model.JobInfoModels.TaskInfoList.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            org.kesy.djob.sdu.api.model.JobInfoModels.TaskInfoList.class,
            org.kesy.djob.sdu.api.model.JobInfoModels.TaskInfoList.getDefaultInstance()));
      }
    }
    
    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }
    
    public interface BlockingInterface {
      public org.kesy.djob.sdu.api.model.JobInfoModels.IntegerType searchJobMonitorCount(
          com.google.protobuf.RpcController controller,
          org.kesy.djob.sdu.api.model.JobMonitorServiceProto.SearchJobMonitorsParam request)
          throws com.google.protobuf.ServiceException;
      
      public org.kesy.djob.sdu.api.model.JobInfoModels.JobInfoList searchJobMonitors(
          com.google.protobuf.RpcController controller,
          org.kesy.djob.sdu.api.model.JobMonitorServiceProto.SearchJobMonitorsParam request)
          throws com.google.protobuf.ServiceException;
      
      public org.kesy.djob.sdu.api.model.JobInfoModels.IntegerType getTaskMonitorCount(
          com.google.protobuf.RpcController controller,
          org.kesy.djob.sdu.api.model.JobInfoModels.StringType request)
          throws com.google.protobuf.ServiceException;
      
      public org.kesy.djob.sdu.api.model.JobInfoModels.TaskInfoList getTaskMonitors(
          com.google.protobuf.RpcController controller,
          org.kesy.djob.sdu.api.model.JobMonitorServiceProto.GetTaskMonitorsParam request)
          throws com.google.protobuf.ServiceException;
      
      public org.kesy.djob.sdu.api.model.JobInfoModels.IntegerType searchJobTaskMonitorCount(
          com.google.protobuf.RpcController controller,
          org.kesy.djob.sdu.api.model.JobMonitorServiceProto.SearchJobMonitorsParam request)
          throws com.google.protobuf.ServiceException;
      
      public org.kesy.djob.sdu.api.model.JobInfoModels.TaskInfoList searchJobTaskMonitors(
          com.google.protobuf.RpcController controller,
          org.kesy.djob.sdu.api.model.JobMonitorServiceProto.SearchJobMonitorsParam request)
          throws com.google.protobuf.ServiceException;
    }
    
    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }
      
      private final com.google.protobuf.BlockingRpcChannel channel;
      
      public org.kesy.djob.sdu.api.model.JobInfoModels.IntegerType searchJobMonitorCount(
          com.google.protobuf.RpcController controller,
          org.kesy.djob.sdu.api.model.JobMonitorServiceProto.SearchJobMonitorsParam request)
          throws com.google.protobuf.ServiceException {
        return (org.kesy.djob.sdu.api.model.JobInfoModels.IntegerType) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          org.kesy.djob.sdu.api.model.JobInfoModels.IntegerType.getDefaultInstance());
      }
      
      
      public org.kesy.djob.sdu.api.model.JobInfoModels.JobInfoList searchJobMonitors(
          com.google.protobuf.RpcController controller,
          org.kesy.djob.sdu.api.model.JobMonitorServiceProto.SearchJobMonitorsParam request)
          throws com.google.protobuf.ServiceException {
        return (org.kesy.djob.sdu.api.model.JobInfoModels.JobInfoList) channel.callBlockingMethod(
          getDescriptor().getMethods().get(1),
          controller,
          request,
          org.kesy.djob.sdu.api.model.JobInfoModels.JobInfoList.getDefaultInstance());
      }
      
      
      public org.kesy.djob.sdu.api.model.JobInfoModels.IntegerType getTaskMonitorCount(
          com.google.protobuf.RpcController controller,
          org.kesy.djob.sdu.api.model.JobInfoModels.StringType request)
          throws com.google.protobuf.ServiceException {
        return (org.kesy.djob.sdu.api.model.JobInfoModels.IntegerType) channel.callBlockingMethod(
          getDescriptor().getMethods().get(2),
          controller,
          request,
          org.kesy.djob.sdu.api.model.JobInfoModels.IntegerType.getDefaultInstance());
      }
      
      
      public org.kesy.djob.sdu.api.model.JobInfoModels.TaskInfoList getTaskMonitors(
          com.google.protobuf.RpcController controller,
          org.kesy.djob.sdu.api.model.JobMonitorServiceProto.GetTaskMonitorsParam request)
          throws com.google.protobuf.ServiceException {
        return (org.kesy.djob.sdu.api.model.JobInfoModels.TaskInfoList) channel.callBlockingMethod(
          getDescriptor().getMethods().get(3),
          controller,
          request,
          org.kesy.djob.sdu.api.model.JobInfoModels.TaskInfoList.getDefaultInstance());
      }
      
      
      public org.kesy.djob.sdu.api.model.JobInfoModels.IntegerType searchJobTaskMonitorCount(
          com.google.protobuf.RpcController controller,
          org.kesy.djob.sdu.api.model.JobMonitorServiceProto.SearchJobMonitorsParam request)
          throws com.google.protobuf.ServiceException {
        return (org.kesy.djob.sdu.api.model.JobInfoModels.IntegerType) channel.callBlockingMethod(
          getDescriptor().getMethods().get(4),
          controller,
          request,
          org.kesy.djob.sdu.api.model.JobInfoModels.IntegerType.getDefaultInstance());
      }
      
      
      public org.kesy.djob.sdu.api.model.JobInfoModels.TaskInfoList searchJobTaskMonitors(
          com.google.protobuf.RpcController controller,
          org.kesy.djob.sdu.api.model.JobMonitorServiceProto.SearchJobMonitorsParam request)
          throws com.google.protobuf.ServiceException {
        return (org.kesy.djob.sdu.api.model.JobInfoModels.TaskInfoList) channel.callBlockingMethod(
          getDescriptor().getMethods().get(5),
          controller,
          request,
          org.kesy.djob.sdu.api.model.JobInfoModels.TaskInfoList.getDefaultInstance());
      }
      
    }
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_kesy_djob_sdu_api_model_SearchJobMonitorsParam_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_kesy_djob_sdu_api_model_SearchJobMonitorsParam_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_kesy_djob_sdu_api_model_GetTaskMonitorsParam_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_kesy_djob_sdu_api_model_GetTaskMonitorsParam_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027JobMonitorService.proto\022\033org.kesy.djob" +
      ".sdu.api.model\032\023JobInfoModels.proto\"\205\001\n\026" +
      "SearchJobMonitorsParam\022\017\n\007jobName\030\001 \001(\t\022" +
      "\021\n\trunStatus\030\002 \001(\t\022\021\n\tpageIndex\030\003 \001(\005\022\020\n" +
      "\010pageSize\030\004 \001(\005\022\021\n\tstartTime\030\005 \001(\t\022\017\n\007en" +
      "dTime\030\006 \001(\t\"J\n\024GetTaskMonitorsParam\022\r\n\005j" +
      "obId\030\001 \001(\t\022\021\n\tpageIndex\030\002 \001(\005\022\020\n\010pageSiz" +
      "e\030\003 \001(\0052\317\005\n\021JobMonitorService\022v\n\025searchJ" +
      "obMonitorCount\0223.org.kesy.djob.sdu.api.m" +
      "odel.SearchJobMonitorsParam\032(.org.kesy.d",
      "job.sdu.api.model.IntegerType\022r\n\021searchJ" +
      "obMonitors\0223.org.kesy.djob.sdu.api.model" +
      ".SearchJobMonitorsParam\032(.org.kesy.djob." +
      "sdu.api.model.JobInfoList\022h\n\023getTaskMoni" +
      "torCount\022\'.org.kesy.djob.sdu.api.model.S" +
      "tringType\032(.org.kesy.djob.sdu.api.model." +
      "IntegerType\022o\n\017getTaskMonitors\0221.org.kes" +
      "y.djob.sdu.api.model.GetTaskMonitorsPara" +
      "m\032).org.kesy.djob.sdu.api.model.TaskInfo" +
      "List\022z\n\031searchJobTaskMonitorCount\0223.org.",
      "kesy.djob.sdu.api.model.SearchJobMonitor" +
      "sParam\032(.org.kesy.djob.sdu.api.model.Int" +
      "egerType\022w\n\025searchJobTaskMonitors\0223.org." +
      "kesy.djob.sdu.api.model.SearchJobMonitor" +
      "sParam\032).org.kesy.djob.sdu.api.model.Tas" +
      "kInfoListB8\n\033org.kesy.djob.sdu.api.model" +
      "B\026JobMonitorServiceProto\210\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_org_kesy_djob_sdu_api_model_SearchJobMonitorsParam_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_org_kesy_djob_sdu_api_model_SearchJobMonitorsParam_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_kesy_djob_sdu_api_model_SearchJobMonitorsParam_descriptor,
              new java.lang.String[] { "JobName", "RunStatus", "PageIndex", "PageSize", "StartTime", "EndTime", },
              org.kesy.djob.sdu.api.model.JobMonitorServiceProto.SearchJobMonitorsParam.class,
              org.kesy.djob.sdu.api.model.JobMonitorServiceProto.SearchJobMonitorsParam.Builder.class);
          internal_static_org_kesy_djob_sdu_api_model_GetTaskMonitorsParam_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_org_kesy_djob_sdu_api_model_GetTaskMonitorsParam_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_kesy_djob_sdu_api_model_GetTaskMonitorsParam_descriptor,
              new java.lang.String[] { "JobId", "PageIndex", "PageSize", },
              org.kesy.djob.sdu.api.model.JobMonitorServiceProto.GetTaskMonitorsParam.class,
              org.kesy.djob.sdu.api.model.JobMonitorServiceProto.GetTaskMonitorsParam.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.kesy.djob.sdu.api.model.JobInfoModels.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
