// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: JobMessageModels.proto

package org.kesy.djob.sdu.api.model;

public final class JobMessageModels {
  private JobMessageModels() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface JobMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional string id = 1;
    boolean hasId();
    String getId();
    
    // optional string name = 2;
    boolean hasName();
    String getName();
    
    // optional string startMode = 3 [default = "auto"];
    boolean hasStartMode();
    String getStartMode();
    
    // optional string execStrategy = 4;
    boolean hasExecStrategy();
    String getExecStrategy();
    
    // optional int64 timeout = 5;
    boolean hasTimeout();
    long getTimeout();
    
    // optional string description = 6;
    boolean hasDescription();
    String getDescription();
    
    // optional string label = 7;
    boolean hasLabel();
    String getLabel();
    
    // optional .org.kesy.djob.sdu.api.model.JobMessage.TaskMessage taskMessage = 8;
    boolean hasTaskMessage();
    org.kesy.djob.sdu.api.model.JobMessageModels.JobMessage.TaskMessage getTaskMessage();
    org.kesy.djob.sdu.api.model.JobMessageModels.JobMessage.TaskMessageOrBuilder getTaskMessageOrBuilder();
    
    // optional string creator = 9;
    boolean hasCreator();
    String getCreator();
    
    // optional string principal = 10;
    boolean hasPrincipal();
    String getPrincipal();
  }
  public static final class JobMessage extends
      com.google.protobuf.GeneratedMessage
      implements JobMessageOrBuilder {
    // Use JobMessage.newBuilder() to construct.
    private JobMessage(Builder builder) {
      super(builder);
    }
    private JobMessage(boolean noInit) {}
    
    private static final JobMessage defaultInstance;
    public static JobMessage getDefaultInstance() {
      return defaultInstance;
    }
    
    public JobMessage getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.kesy.djob.sdu.api.model.JobMessageModels.internal_static_org_kesy_djob_sdu_api_model_JobMessage_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.kesy.djob.sdu.api.model.JobMessageModels.internal_static_org_kesy_djob_sdu_api_model_JobMessage_fieldAccessorTable;
    }
    
    public interface TaskMessageOrBuilder
        extends com.google.protobuf.MessageOrBuilder {
      
      // optional string execName = 1;
      boolean hasExecName();
      String getExecName();
      
      // optional string execParam = 2;
      boolean hasExecParam();
      String getExecParam();
    }
    public static final class TaskMessage extends
        com.google.protobuf.GeneratedMessage
        implements TaskMessageOrBuilder {
      // Use TaskMessage.newBuilder() to construct.
      private TaskMessage(Builder builder) {
        super(builder);
      }
      private TaskMessage(boolean noInit) {}
      
      private static final TaskMessage defaultInstance;
      public static TaskMessage getDefaultInstance() {
        return defaultInstance;
      }
      
      public TaskMessage getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.kesy.djob.sdu.api.model.JobMessageModels.internal_static_org_kesy_djob_sdu_api_model_JobMessage_TaskMessage_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.kesy.djob.sdu.api.model.JobMessageModels.internal_static_org_kesy_djob_sdu_api_model_JobMessage_TaskMessage_fieldAccessorTable;
      }
      
      private int bitField0_;
      // optional string execName = 1;
      public static final int EXECNAME_FIELD_NUMBER = 1;
      private java.lang.Object execName_;
      public boolean hasExecName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getExecName() {
        java.lang.Object ref = execName_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (com.google.protobuf.Internal.isValidUtf8(bs)) {
            execName_ = s;
          }
          return s;
        }
      }
      private com.google.protobuf.ByteString getExecNameBytes() {
        java.lang.Object ref = execName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8((String) ref);
          execName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      
      // optional string execParam = 2;
      public static final int EXECPARAM_FIELD_NUMBER = 2;
      private java.lang.Object execParam_;
      public boolean hasExecParam() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getExecParam() {
        java.lang.Object ref = execParam_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (com.google.protobuf.Internal.isValidUtf8(bs)) {
            execParam_ = s;
          }
          return s;
        }
      }
      private com.google.protobuf.ByteString getExecParamBytes() {
        java.lang.Object ref = execParam_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8((String) ref);
          execParam_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      
      private void initFields() {
        execName_ = "";
        execParam_ = "";
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;
        
        memoizedIsInitialized = 1;
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getExecNameBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, getExecParamBytes());
        }
        getUnknownFields().writeTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getExecNameBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, getExecParamBytes());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }
      
      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }
      
      public static org.kesy.djob.sdu.api.model.JobMessageModels.JobMessage.TaskMessage parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static org.kesy.djob.sdu.api.model.JobMessageModels.JobMessage.TaskMessage parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static org.kesy.djob.sdu.api.model.JobMessageModels.JobMessage.TaskMessage parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static org.kesy.djob.sdu.api.model.JobMessageModels.JobMessage.TaskMessage parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static org.kesy.djob.sdu.api.model.JobMessageModels.JobMessage.TaskMessage parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static org.kesy.djob.sdu.api.model.JobMessageModels.JobMessage.TaskMessage parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static org.kesy.djob.sdu.api.model.JobMessageModels.JobMessage.TaskMessage parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static org.kesy.djob.sdu.api.model.JobMessageModels.JobMessage.TaskMessage parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static org.kesy.djob.sdu.api.model.JobMessageModels.JobMessage.TaskMessage parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static org.kesy.djob.sdu.api.model.JobMessageModels.JobMessage.TaskMessage parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(org.kesy.djob.sdu.api.model.JobMessageModels.JobMessage.TaskMessage prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements org.kesy.djob.sdu.api.model.JobMessageModels.JobMessage.TaskMessageOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return org.kesy.djob.sdu.api.model.JobMessageModels.internal_static_org_kesy_djob_sdu_api_model_JobMessage_TaskMessage_descriptor;
        }
        
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return org.kesy.djob.sdu.api.model.JobMessageModels.internal_static_org_kesy_djob_sdu_api_model_JobMessage_TaskMessage_fieldAccessorTable;
        }
        
        // Construct using org.kesy.djob.sdu.api.model.JobMessageModels.JobMessage.TaskMessage.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }
        
        private Builder(BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }
        
        public Builder clear() {
          super.clear();
          execName_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          execParam_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }
        
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return org.kesy.djob.sdu.api.model.JobMessageModels.JobMessage.TaskMessage.getDescriptor();
        }
        
        public org.kesy.djob.sdu.api.model.JobMessageModels.JobMessage.TaskMessage getDefaultInstanceForType() {
          return org.kesy.djob.sdu.api.model.JobMessageModels.JobMessage.TaskMessage.getDefaultInstance();
        }
        
        public org.kesy.djob.sdu.api.model.JobMessageModels.JobMessage.TaskMessage build() {
          org.kesy.djob.sdu.api.model.JobMessageModels.JobMessage.TaskMessage result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }
        
        private org.kesy.djob.sdu.api.model.JobMessageModels.JobMessage.TaskMessage buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          org.kesy.djob.sdu.api.model.JobMessageModels.JobMessage.TaskMessage result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return result;
        }
        
        public org.kesy.djob.sdu.api.model.JobMessageModels.JobMessage.TaskMessage buildPartial() {
          org.kesy.djob.sdu.api.model.JobMessageModels.JobMessage.TaskMessage result = new org.kesy.djob.sdu.api.model.JobMessageModels.JobMessage.TaskMessage(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.execName_ = execName_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.execParam_ = execParam_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }
        
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof org.kesy.djob.sdu.api.model.JobMessageModels.JobMessage.TaskMessage) {
            return mergeFrom((org.kesy.djob.sdu.api.model.JobMessageModels.JobMessage.TaskMessage)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
        
        public Builder mergeFrom(org.kesy.djob.sdu.api.model.JobMessageModels.JobMessage.TaskMessage other) {
          if (other == org.kesy.djob.sdu.api.model.JobMessageModels.JobMessage.TaskMessage.getDefaultInstance()) return this;
          if (other.hasExecName()) {
            setExecName(other.getExecName());
          }
          if (other.hasExecParam()) {
            setExecParam(other.getExecParam());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }
        
        public final boolean isInitialized() {
          return true;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  onChanged();
                  return this;
                }
                break;
              }
              case 10: {
                bitField0_ |= 0x00000001;
                execName_ = input.readBytes();
                break;
              }
              case 18: {
                bitField0_ |= 0x00000002;
                execParam_ = input.readBytes();
                break;
              }
            }
          }
        }
        
        private int bitField0_;
        
        // optional string execName = 1;
        private java.lang.Object execName_ = "";
        public boolean hasExecName() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        public String getExecName() {
          java.lang.Object ref = execName_;
          if (!(ref instanceof String)) {
            String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
            execName_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        public Builder setExecName(String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          execName_ = value;
          onChanged();
          return this;
        }
        public Builder clearExecName() {
          bitField0_ = (bitField0_ & ~0x00000001);
          execName_ = getDefaultInstance().getExecName();
          onChanged();
          return this;
        }
        void setExecName(com.google.protobuf.ByteString value) {
          bitField0_ |= 0x00000001;
          execName_ = value;
          onChanged();
        }
        
        // optional string execParam = 2;
        private java.lang.Object execParam_ = "";
        public boolean hasExecParam() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        public String getExecParam() {
          java.lang.Object ref = execParam_;
          if (!(ref instanceof String)) {
            String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
            execParam_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        public Builder setExecParam(String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          execParam_ = value;
          onChanged();
          return this;
        }
        public Builder clearExecParam() {
          bitField0_ = (bitField0_ & ~0x00000002);
          execParam_ = getDefaultInstance().getExecParam();
          onChanged();
          return this;
        }
        void setExecParam(com.google.protobuf.ByteString value) {
          bitField0_ |= 0x00000002;
          execParam_ = value;
          onChanged();
        }
        
        // @@protoc_insertion_point(builder_scope:org.kesy.djob.sdu.api.model.JobMessage.TaskMessage)
      }
      
      static {
        defaultInstance = new TaskMessage(true);
        defaultInstance.initFields();
      }
      
      // @@protoc_insertion_point(class_scope:org.kesy.djob.sdu.api.model.JobMessage.TaskMessage)
    }
    
    private int bitField0_;
    // optional string id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private java.lang.Object id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          id_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string name = 2;
    public static final int NAME_FIELD_NUMBER = 2;
    private java.lang.Object name_;
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          name_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string startMode = 3 [default = "auto"];
    public static final int STARTMODE_FIELD_NUMBER = 3;
    private java.lang.Object startMode_;
    public boolean hasStartMode() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getStartMode() {
      java.lang.Object ref = startMode_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          startMode_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getStartModeBytes() {
      java.lang.Object ref = startMode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        startMode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string execStrategy = 4;
    public static final int EXECSTRATEGY_FIELD_NUMBER = 4;
    private java.lang.Object execStrategy_;
    public boolean hasExecStrategy() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getExecStrategy() {
      java.lang.Object ref = execStrategy_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          execStrategy_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getExecStrategyBytes() {
      java.lang.Object ref = execStrategy_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        execStrategy_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int64 timeout = 5;
    public static final int TIMEOUT_FIELD_NUMBER = 5;
    private long timeout_;
    public boolean hasTimeout() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public long getTimeout() {
      return timeout_;
    }
    
    // optional string description = 6;
    public static final int DESCRIPTION_FIELD_NUMBER = 6;
    private java.lang.Object description_;
    public boolean hasDescription() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          description_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string label = 7;
    public static final int LABEL_FIELD_NUMBER = 7;
    private java.lang.Object label_;
    public boolean hasLabel() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public String getLabel() {
      java.lang.Object ref = label_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          label_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getLabelBytes() {
      java.lang.Object ref = label_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        label_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional .org.kesy.djob.sdu.api.model.JobMessage.TaskMessage taskMessage = 8;
    public static final int TASKMESSAGE_FIELD_NUMBER = 8;
    private org.kesy.djob.sdu.api.model.JobMessageModels.JobMessage.TaskMessage taskMessage_;
    public boolean hasTaskMessage() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    public org.kesy.djob.sdu.api.model.JobMessageModels.JobMessage.TaskMessage getTaskMessage() {
      return taskMessage_;
    }
    public org.kesy.djob.sdu.api.model.JobMessageModels.JobMessage.TaskMessageOrBuilder getTaskMessageOrBuilder() {
      return taskMessage_;
    }
    
    // optional string creator = 9;
    public static final int CREATOR_FIELD_NUMBER = 9;
    private java.lang.Object creator_;
    public boolean hasCreator() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    public String getCreator() {
      java.lang.Object ref = creator_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          creator_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getCreatorBytes() {
      java.lang.Object ref = creator_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        creator_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string principal = 10;
    public static final int PRINCIPAL_FIELD_NUMBER = 10;
    private java.lang.Object principal_;
    public boolean hasPrincipal() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    public String getPrincipal() {
      java.lang.Object ref = principal_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          principal_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getPrincipalBytes() {
      java.lang.Object ref = principal_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        principal_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      id_ = "";
      name_ = "";
      startMode_ = "auto";
      execStrategy_ = "";
      timeout_ = 0L;
      description_ = "";
      label_ = "";
      taskMessage_ = org.kesy.djob.sdu.api.model.JobMessageModels.JobMessage.TaskMessage.getDefaultInstance();
      creator_ = "";
      principal_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getStartModeBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getExecStrategyBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt64(5, timeout_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getDescriptionBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getLabelBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeMessage(8, taskMessage_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBytes(9, getCreatorBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeBytes(10, getPrincipalBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getStartModeBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getExecStrategyBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, timeout_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getDescriptionBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getLabelBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(8, taskMessage_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, getCreatorBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(10, getPrincipalBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.kesy.djob.sdu.api.model.JobMessageModels.JobMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.kesy.djob.sdu.api.model.JobMessageModels.JobMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.kesy.djob.sdu.api.model.JobMessageModels.JobMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.kesy.djob.sdu.api.model.JobMessageModels.JobMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.kesy.djob.sdu.api.model.JobMessageModels.JobMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.kesy.djob.sdu.api.model.JobMessageModels.JobMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.kesy.djob.sdu.api.model.JobMessageModels.JobMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.kesy.djob.sdu.api.model.JobMessageModels.JobMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.kesy.djob.sdu.api.model.JobMessageModels.JobMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.kesy.djob.sdu.api.model.JobMessageModels.JobMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.kesy.djob.sdu.api.model.JobMessageModels.JobMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.kesy.djob.sdu.api.model.JobMessageModels.JobMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.kesy.djob.sdu.api.model.JobMessageModels.internal_static_org_kesy_djob_sdu_api_model_JobMessage_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.kesy.djob.sdu.api.model.JobMessageModels.internal_static_org_kesy_djob_sdu_api_model_JobMessage_fieldAccessorTable;
      }
      
      // Construct using org.kesy.djob.sdu.api.model.JobMessageModels.JobMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getTaskMessageFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        startMode_ = "auto";
        bitField0_ = (bitField0_ & ~0x00000004);
        execStrategy_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        timeout_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        description_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        label_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        if (taskMessageBuilder_ == null) {
          taskMessage_ = org.kesy.djob.sdu.api.model.JobMessageModels.JobMessage.TaskMessage.getDefaultInstance();
        } else {
          taskMessageBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000080);
        creator_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        principal_ = "";
        bitField0_ = (bitField0_ & ~0x00000200);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.kesy.djob.sdu.api.model.JobMessageModels.JobMessage.getDescriptor();
      }
      
      public org.kesy.djob.sdu.api.model.JobMessageModels.JobMessage getDefaultInstanceForType() {
        return org.kesy.djob.sdu.api.model.JobMessageModels.JobMessage.getDefaultInstance();
      }
      
      public org.kesy.djob.sdu.api.model.JobMessageModels.JobMessage build() {
        org.kesy.djob.sdu.api.model.JobMessageModels.JobMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.kesy.djob.sdu.api.model.JobMessageModels.JobMessage buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.kesy.djob.sdu.api.model.JobMessageModels.JobMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.kesy.djob.sdu.api.model.JobMessageModels.JobMessage buildPartial() {
        org.kesy.djob.sdu.api.model.JobMessageModels.JobMessage result = new org.kesy.djob.sdu.api.model.JobMessageModels.JobMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.startMode_ = startMode_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.execStrategy_ = execStrategy_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.timeout_ = timeout_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.description_ = description_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.label_ = label_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        if (taskMessageBuilder_ == null) {
          result.taskMessage_ = taskMessage_;
        } else {
          result.taskMessage_ = taskMessageBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.creator_ = creator_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.principal_ = principal_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.kesy.djob.sdu.api.model.JobMessageModels.JobMessage) {
          return mergeFrom((org.kesy.djob.sdu.api.model.JobMessageModels.JobMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.kesy.djob.sdu.api.model.JobMessageModels.JobMessage other) {
        if (other == org.kesy.djob.sdu.api.model.JobMessageModels.JobMessage.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasStartMode()) {
          setStartMode(other.getStartMode());
        }
        if (other.hasExecStrategy()) {
          setExecStrategy(other.getExecStrategy());
        }
        if (other.hasTimeout()) {
          setTimeout(other.getTimeout());
        }
        if (other.hasDescription()) {
          setDescription(other.getDescription());
        }
        if (other.hasLabel()) {
          setLabel(other.getLabel());
        }
        if (other.hasTaskMessage()) {
          mergeTaskMessage(other.getTaskMessage());
        }
        if (other.hasCreator()) {
          setCreator(other.getCreator());
        }
        if (other.hasPrincipal()) {
          setPrincipal(other.getPrincipal());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              id_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              name_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              startMode_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              execStrategy_ = input.readBytes();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              timeout_ = input.readInt64();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              description_ = input.readBytes();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              label_ = input.readBytes();
              break;
            }
            case 66: {
              org.kesy.djob.sdu.api.model.JobMessageModels.JobMessage.TaskMessage.Builder subBuilder = org.kesy.djob.sdu.api.model.JobMessageModels.JobMessage.TaskMessage.newBuilder();
              if (hasTaskMessage()) {
                subBuilder.mergeFrom(getTaskMessage());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setTaskMessage(subBuilder.buildPartial());
              break;
            }
            case 74: {
              bitField0_ |= 0x00000100;
              creator_ = input.readBytes();
              break;
            }
            case 82: {
              bitField0_ |= 0x00000200;
              principal_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string id = 1;
      private java.lang.Object id_ = "";
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      void setId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
      }
      
      // optional string name = 2;
      private java.lang.Object name_ = "";
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      void setName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
      }
      
      // optional string startMode = 3 [default = "auto"];
      private java.lang.Object startMode_ = "auto";
      public boolean hasStartMode() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getStartMode() {
        java.lang.Object ref = startMode_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          startMode_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setStartMode(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        startMode_ = value;
        onChanged();
        return this;
      }
      public Builder clearStartMode() {
        bitField0_ = (bitField0_ & ~0x00000004);
        startMode_ = getDefaultInstance().getStartMode();
        onChanged();
        return this;
      }
      void setStartMode(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        startMode_ = value;
        onChanged();
      }
      
      // optional string execStrategy = 4;
      private java.lang.Object execStrategy_ = "";
      public boolean hasExecStrategy() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getExecStrategy() {
        java.lang.Object ref = execStrategy_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          execStrategy_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setExecStrategy(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        execStrategy_ = value;
        onChanged();
        return this;
      }
      public Builder clearExecStrategy() {
        bitField0_ = (bitField0_ & ~0x00000008);
        execStrategy_ = getDefaultInstance().getExecStrategy();
        onChanged();
        return this;
      }
      void setExecStrategy(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        execStrategy_ = value;
        onChanged();
      }
      
      // optional int64 timeout = 5;
      private long timeout_ ;
      public boolean hasTimeout() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public long getTimeout() {
        return timeout_;
      }
      public Builder setTimeout(long value) {
        bitField0_ |= 0x00000010;
        timeout_ = value;
        onChanged();
        return this;
      }
      public Builder clearTimeout() {
        bitField0_ = (bitField0_ & ~0x00000010);
        timeout_ = 0L;
        onChanged();
        return this;
      }
      
      // optional string description = 6;
      private java.lang.Object description_ = "";
      public boolean hasDescription() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          description_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setDescription(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        description_ = value;
        onChanged();
        return this;
      }
      public Builder clearDescription() {
        bitField0_ = (bitField0_ & ~0x00000020);
        description_ = getDefaultInstance().getDescription();
        onChanged();
        return this;
      }
      void setDescription(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000020;
        description_ = value;
        onChanged();
      }
      
      // optional string label = 7;
      private java.lang.Object label_ = "";
      public boolean hasLabel() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public String getLabel() {
        java.lang.Object ref = label_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          label_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setLabel(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        label_ = value;
        onChanged();
        return this;
      }
      public Builder clearLabel() {
        bitField0_ = (bitField0_ & ~0x00000040);
        label_ = getDefaultInstance().getLabel();
        onChanged();
        return this;
      }
      void setLabel(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000040;
        label_ = value;
        onChanged();
      }
      
      // optional .org.kesy.djob.sdu.api.model.JobMessage.TaskMessage taskMessage = 8;
      private org.kesy.djob.sdu.api.model.JobMessageModels.JobMessage.TaskMessage taskMessage_ = org.kesy.djob.sdu.api.model.JobMessageModels.JobMessage.TaskMessage.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          org.kesy.djob.sdu.api.model.JobMessageModels.JobMessage.TaskMessage, org.kesy.djob.sdu.api.model.JobMessageModels.JobMessage.TaskMessage.Builder, org.kesy.djob.sdu.api.model.JobMessageModels.JobMessage.TaskMessageOrBuilder> taskMessageBuilder_;
      public boolean hasTaskMessage() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      public org.kesy.djob.sdu.api.model.JobMessageModels.JobMessage.TaskMessage getTaskMessage() {
        if (taskMessageBuilder_ == null) {
          return taskMessage_;
        } else {
          return taskMessageBuilder_.getMessage();
        }
      }
      public Builder setTaskMessage(org.kesy.djob.sdu.api.model.JobMessageModels.JobMessage.TaskMessage value) {
        if (taskMessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          taskMessage_ = value;
          onChanged();
        } else {
          taskMessageBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000080;
        return this;
      }
      public Builder setTaskMessage(
          org.kesy.djob.sdu.api.model.JobMessageModels.JobMessage.TaskMessage.Builder builderForValue) {
        if (taskMessageBuilder_ == null) {
          taskMessage_ = builderForValue.build();
          onChanged();
        } else {
          taskMessageBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000080;
        return this;
      }
      public Builder mergeTaskMessage(org.kesy.djob.sdu.api.model.JobMessageModels.JobMessage.TaskMessage value) {
        if (taskMessageBuilder_ == null) {
          if (((bitField0_ & 0x00000080) == 0x00000080) &&
              taskMessage_ != org.kesy.djob.sdu.api.model.JobMessageModels.JobMessage.TaskMessage.getDefaultInstance()) {
            taskMessage_ =
              org.kesy.djob.sdu.api.model.JobMessageModels.JobMessage.TaskMessage.newBuilder(taskMessage_).mergeFrom(value).buildPartial();
          } else {
            taskMessage_ = value;
          }
          onChanged();
        } else {
          taskMessageBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000080;
        return this;
      }
      public Builder clearTaskMessage() {
        if (taskMessageBuilder_ == null) {
          taskMessage_ = org.kesy.djob.sdu.api.model.JobMessageModels.JobMessage.TaskMessage.getDefaultInstance();
          onChanged();
        } else {
          taskMessageBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }
      public org.kesy.djob.sdu.api.model.JobMessageModels.JobMessage.TaskMessage.Builder getTaskMessageBuilder() {
        bitField0_ |= 0x00000080;
        onChanged();
        return getTaskMessageFieldBuilder().getBuilder();
      }
      public org.kesy.djob.sdu.api.model.JobMessageModels.JobMessage.TaskMessageOrBuilder getTaskMessageOrBuilder() {
        if (taskMessageBuilder_ != null) {
          return taskMessageBuilder_.getMessageOrBuilder();
        } else {
          return taskMessage_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          org.kesy.djob.sdu.api.model.JobMessageModels.JobMessage.TaskMessage, org.kesy.djob.sdu.api.model.JobMessageModels.JobMessage.TaskMessage.Builder, org.kesy.djob.sdu.api.model.JobMessageModels.JobMessage.TaskMessageOrBuilder> 
          getTaskMessageFieldBuilder() {
        if (taskMessageBuilder_ == null) {
          taskMessageBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              org.kesy.djob.sdu.api.model.JobMessageModels.JobMessage.TaskMessage, org.kesy.djob.sdu.api.model.JobMessageModels.JobMessage.TaskMessage.Builder, org.kesy.djob.sdu.api.model.JobMessageModels.JobMessage.TaskMessageOrBuilder>(
                  taskMessage_,
                  getParentForChildren(),
                  isClean());
          taskMessage_ = null;
        }
        return taskMessageBuilder_;
      }
      
      // optional string creator = 9;
      private java.lang.Object creator_ = "";
      public boolean hasCreator() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      public String getCreator() {
        java.lang.Object ref = creator_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          creator_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setCreator(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        creator_ = value;
        onChanged();
        return this;
      }
      public Builder clearCreator() {
        bitField0_ = (bitField0_ & ~0x00000100);
        creator_ = getDefaultInstance().getCreator();
        onChanged();
        return this;
      }
      void setCreator(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000100;
        creator_ = value;
        onChanged();
      }
      
      // optional string principal = 10;
      private java.lang.Object principal_ = "";
      public boolean hasPrincipal() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      public String getPrincipal() {
        java.lang.Object ref = principal_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          principal_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setPrincipal(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        principal_ = value;
        onChanged();
        return this;
      }
      public Builder clearPrincipal() {
        bitField0_ = (bitField0_ & ~0x00000200);
        principal_ = getDefaultInstance().getPrincipal();
        onChanged();
        return this;
      }
      void setPrincipal(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000200;
        principal_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:org.kesy.djob.sdu.api.model.JobMessage)
    }
    
    static {
      defaultInstance = new JobMessage(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:org.kesy.djob.sdu.api.model.JobMessage)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_kesy_djob_sdu_api_model_JobMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_kesy_djob_sdu_api_model_JobMessage_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_kesy_djob_sdu_api_model_JobMessage_TaskMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_kesy_djob_sdu_api_model_JobMessage_TaskMessage_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026JobMessageModels.proto\022\033org.kesy.djob." +
      "sdu.api.model\"\254\002\n\nJobMessage\022\n\n\002id\030\001 \001(\t" +
      "\022\014\n\004name\030\002 \001(\t\022\027\n\tstartMode\030\003 \001(\t:\004auto\022" +
      "\024\n\014execStrategy\030\004 \001(\t\022\017\n\007timeout\030\005 \001(\003\022\023" +
      "\n\013description\030\006 \001(\t\022\r\n\005label\030\007 \001(\t\022H\n\013ta" +
      "skMessage\030\010 \001(\01323.org.kesy.djob.sdu.api." +
      "model.JobMessage.TaskMessage\022\017\n\007creator\030" +
      "\t \001(\t\022\021\n\tprincipal\030\n \001(\t\0322\n\013TaskMessage\022" +
      "\020\n\010execName\030\001 \001(\t\022\021\n\texecParam\030\002 \001(\tB2\n\033" +
      "org.kesy.djob.sdu.api.modelB\020JobMessageM",
      "odels\210\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_org_kesy_djob_sdu_api_model_JobMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_org_kesy_djob_sdu_api_model_JobMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_kesy_djob_sdu_api_model_JobMessage_descriptor,
              new java.lang.String[] { "Id", "Name", "StartMode", "ExecStrategy", "Timeout", "Description", "Label", "TaskMessage", "Creator", "Principal", },
              org.kesy.djob.sdu.api.model.JobMessageModels.JobMessage.class,
              org.kesy.djob.sdu.api.model.JobMessageModels.JobMessage.Builder.class);
          internal_static_org_kesy_djob_sdu_api_model_JobMessage_TaskMessage_descriptor =
            internal_static_org_kesy_djob_sdu_api_model_JobMessage_descriptor.getNestedTypes().get(0);
          internal_static_org_kesy_djob_sdu_api_model_JobMessage_TaskMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_kesy_djob_sdu_api_model_JobMessage_TaskMessage_descriptor,
              new java.lang.String[] { "ExecName", "ExecParam", },
              org.kesy.djob.sdu.api.model.JobMessageModels.JobMessage.TaskMessage.class,
              org.kesy.djob.sdu.api.model.JobMessageModels.JobMessage.TaskMessage.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
